### ISSUE TITLE
For scenario/project/masterclass creation-Time to complete is accepting first character as a letter (only alphabet E worked)

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#36]
Steps:

1. Login/Launch https://www.stag-creator.enqurious.com/
2. Click + for scenario to create a scenario.
3. While filling up the fields, enter letter 'E' for 'Time to complete'.
4. Expected Result: The letter E is not accepted and only numerals have to be accepted.
5. Actual Result: The letter is accepted as first character but not from second character.

Screenshot:
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/f9e949b6-4adc-4d10-87c9-150e570f9b73)

**Comment by sheetalguptamahankali** [comment]
Also, the field is accepting numbers without a maximum cap, just in case if you want to limit that.
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/784b58aa-16a3-4115-bb73-3ebf50e6e701)

**Comment by sheetalguptamahankali** [comment]
For project creation, the price field is also accepting E as first character

**Comment by mskl-kashish** [comment]
@sheetalguptamahankali  This issue has been fixed , please test and close it.

**Comment by sheetalguptamahankali** [comment]
This is still not fixed, I cannot use 'e' anymore but still can use 'E'. Screenshot below
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/e45e4ea0-1b83-40b7-b139-08ea672ab444)

**Comment by mskl-kashish** [comment]
@sheetalguptamahankali This issue has been fixed , please test and close it.

**Comment by sheetalguptamahankali** [comment]
This is working fine. So, closing it
